name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-progress --no-interaction --prefer-dist

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    # agar tum JS/Tailwind/Vite use karte ho
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install NPM dependencies
      run: npm install

    - name: Build assets
      run: npm run build

    - name: PHP lint check
      run: find ./ -type f -name "*.php" -exec php -l {} \;
