name: CI Workflow

# Minimal permissions for security
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Build Project
        run: npm run build

      # Step 5: Run tests (optional)
      - name: Run Tests
        run: |
          if npm run test --if-present; then
            echo "Tests passed"
          else
            echo "No tests configured or tests failed, continuing..."
          fi
